name: 'Portainer Deploy Stack'
description: 'Deploy provided stack via Portainer'
inputs:
  portainer-username:
    description: Poratainer user name
    required: true

  portainer-password:
    description: Portainer user password
    required: true

  portainer-url:
    description: URL of Portainer instance
    required: true

  portainer-endpoint:
    description: Swarm cluster ID in Portainer
    required: true

  stack-name: 
    description: Docker Swarm stack name
    required: true

  stack-file:
    description: Path of file with stack definition
    required: true

  stack-vars:
    description: Stack variables to substitute.
    required: false

  teams:
    description: |
      Name of teams who can access this stack via Poratiner. 
      Delimited by ","
    required: false
  
outputs:
  stack_id:
    description: Created docker swarm stack ID

runs:
  using: 'node12'
  main: 'dist/index.js'